### PR TITLE
Add launcher icon

### PR DESCRIPTION
**Pull request by deveshd2k**
Design for logo proposed

### CODE REVIEW

**Comment by Kartikdot** [comment]
The file name of the icons should "icon.png". Since the code looks for a file named the same. It cannot be "icons1.png" or anything else. Please make the required changes and commit them to "dklogo" branch in your repo. They will be reflected here too.

**Comment by deveshd2k** [comment]
but the folder already contains icon.png file so i can't change my filename

**Comment by deveshd2k** [comment]
Changes done. Review the pr.

**Comment by Kartikdot** [comment]
Thanks ! Happy hacktoberfest !

**Pull request merged**
